# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-28 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pwd', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dashboard.UserLevel'),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_msgs', to='dashboard.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_msgs', to='dashboard.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='cmt_poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_cmts', to='dashboard.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='cmt_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_cmts', to='dashboard.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='msg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiedto_cmts', to='dashboard.Message'),
        ),
    ]
