# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-29 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180128_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cmt_receiver',
        ),
    ]
